### ISSUE TITLE
Whether handler.go.tmpl is correct or not

### ISSUE THREAD

**Issue by xiaoshangquan** [operator-framework/getting-started#15]
import      
 "github.com/operator-framework/operator-sdk/pkg/sdk/action"
	"github.com/operator-framework/operator-sdk/pkg/sdk/handler"
	"github.com/operator-framework/operator-sdk/pkg/sdk/query"
	"github.com/operator-framework/operator-sdk/pkg/sdk/types"

action、handler、query、types is not package. I can't import  its.

**Comment by pb82** [comment]
It appears they have all been moved to `sdk`. Something like this should work: https://gist.github.com/pb82/cb5e6be48114875b5695f35589bfc8a6
