### ISSUE TITLE
Error while deploying the operator via OLM

### ISSUE THREAD

**Issue by darkowlzz** [operator-framework/getting-started#21]
I was following the Getting Started Guide's [Deploy the Operator](https://github.com/operator-framework/getting-started#manage-the-operator-using-the-operator-lifecycle-manager) section and tried to install memcachedoperator csv after deploying OLM, but I got this error:
```
$ kubectl apply -f memcachedoperator.0.0.1.csv.yaml
error: unable to recognize "memcachedoperator.0.0.1.csv.yaml": no matches for kind "ClusterServiceVersion-v1" in version "app.coreos.com/v1alpha1"
```
I also tried removing `-v1` from `ClusterServiceVersion-v1` in the file, but I get the same error:
```
$ kubectl apply -f memcachedoperator.0.0.1.csv.yaml 
error: unable to recognize "memcachedoperator.0.0.1.csv.yaml": no matches for kind "ClusterServiceVersion" in version "app.coreos.com/v1alpha1"
``` 
I'm not aware of much of the internals of OLM at the moment. Some hint would be great.

**Comment by robszumski** [comment]
Can you try removing `-v1` _and_ using `operators.coreos.com/v1alpha1` instead of `app.coreos.com/v1alpha1`? If that works, we can update the docs.

cc @ecordell

**Comment by darkowlzz** [comment]
@robszumski That worked. Thanks!
I see that csv is in `operators.coreos.com` group here https://github.com/operator-framework/operator-lifecycle-manager/blob/master/deploy/upstream/manifests/0.7.0/03-clusterserviceversion.crd.yaml#L37 .

**Comment by smanpathak** [comment]
I am hitting something similar. OLM logs --
time="2018-12-04T22:09:40Z" level=info msg="error updating ClusterServiceVersion status: the server could not find the requested resource (put clusterserviceversions.operators.coreos.com memcachedoperator.v0.0.1)" csv=memcachedoperator.v0.0.1 namespace=default phase=
