### ISSUE TITLE
OLM cannot update memcached operator CSV

### ISSUE THREAD

**Issue by smanpathak** [operator-framework/getting-started#31]
I followed guides to deploy upstream olm on minikube. Then created a memcached operator. I applied the CRD and role, sa and sa-binding from deploy directory of memcached scaffold.

Now, OLM cannot update CSV status with error:
level=info msg="error updating ClusterServiceVersion status: the server could not find the requested resource (put clusterserviceversions.operators.coreos.com memcachedoperator.v0.0.1)" csv=memcachedoperator.v0.0.1 namespace=default phase=

Strange thing is, it can list the CSVs using same client and that list contains memcachedoperator

**Comment by smanpathak** [comment]
Looks like "status" field is missing from CSV spec. I can't find similar field here: https://github.com/operator-framework/operator-lifecycle-manager/blob/master/deploy/chart/catalog_resources/rh-operators/etcdoperator.v0.9.2.clusterserviceversion.yaml as well.

**Comment by smanpathak** [comment]
I removed subresource from updatestatus call --
result = &v1alpha1.ClusterServiceVersion{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("clusterserviceversions").
		Name(clusterServiceVersion.Name).
		//SubResource("status").
		Body(clusterServiceVersion).
		Do().
		Into(result)

And then it started working.

**Comment by smanpathak** [comment]
Another issue is that the CSV specifies policyrule as '*' for API groups, resources and verbs while the operator creates a finer RBAC policy for memcached-operator. They don't match and CSV remains in pending state.

**Comment by dongwenjuan** [comment]
Does the issue resolved? It also happend to me, error log from olm-operator:

1)  time="2019-02-20T06:59:38Z" level=info msg="not in operatorgroup namespace, skipping" csv=memcachedoperator.v0.0.1 namespace=olm phase=
solution: modify the namespace to olm for memcached-operator
2）time="2019-02-20T06:59:38Z" level=warning msg="installmodes not supported" csv=memcachedoperator.v0.0.1 err="SingleNamespace InstallModeType not supported, cannot configure to watch one namespace" namespace=olm opgroup=olm-operators phase=
solution：add installModes in csv file
installModes:
 - type: SingleNamespace
   supported: true
3）time="2019-02-20T07:13:35Z" level=info msg="requirements were not met" csv=memcachedoperator.v0.0.1 namespace=olm phase=Pending

Use `kubectl get csv memcachedoperator.v0.0.1 -o yaml -n olm` to get the detail:
  - dependents:
    - group: rbac.authorization.k8s.io
      kind: PolicyRule
      message: namespaced rule:{"verbs":["*"],"apiGroups":["*"],"resources":["*"]}
      status: NotSatisfied
      version: v1beta1
    group: ""
    kind: ServiceAccount
    message: Policy rule not satisfied for service account
    name: memcached-operator
    status: PresentNotSatisfied
    version: v1

So how do I modify the policyrule? I tried many policyrule configuration, but all failed. Can anybody help? Thanks~

**Comment by camilamacedo86** [comment]
The OLM steps in the Getting Started as its example was updated in the #57 in order to address this issue as well. Then, I am closing this task. However, please, feel free to re-open if you see that still required.
