### ISSUE TITLE
Documentation - cannot install memcached CSV

### ISSUE THREAD

**Issue by jpkrohling** [operator-framework/getting-started#34]
Following the readme, it shows the following command to install the memcached CSV:

```console
$ curl -Lo memcachedoperator.0.0.1.csv.yaml https://raw.githubusercontent.com/operator-framework/getting-started/master/memcachedoperator.0.0.1.csv.yaml
$ kubectl apply -f memcachedoperator.0.0.1.csv.yaml
```

This CSV isn't successfully installed:

```console
$ kubectl describe ClusterServiceVersion -n default
...
Status:
  Certs Last Updated:  <nil>
  Certs Rotate At:     <nil>
  Conditions:
    Last Transition Time:  2019-03-29T10:47:20Z
    Last Update Time:      2019-03-29T10:47:20Z
    Message:               csv in namespace with no operatorgroups
    Phase:                 Failed
    Reason:                NoOperatorGroup
  Last Transition Time:    2019-03-29T10:47:20Z
  Last Update Time:        2019-03-29T10:51:23Z
  Message:                 csv in namespace with no operatorgroups
  Phase:                   Failed
  Reason:                  NoOperatorGroup
Events:
  Type     Reason           Age               From                        Message
  ----     ------           ----              ----                        -------
  Warning  NoOperatorGroup  3m (x25 over 4m)  operator-lifecycle-manager  csv in namespace with no operatorgroups

```

**Comment by SamiSousa** [comment]
Seems like this getting started guide is very out of date with the current version of OLM. You can follow the instructions here: https://github.com/operator-framework/operator-lifecycle-manager/blob/master/Documentation/design/building-your-csv.md to create a CSV.
The docs here: https://github.com/operator-framework/operator-lifecycle-manager/blob/master/Documentation/design/operatorgroups.md explain OperatorGroups and multitenancy with OLM.
To install a CSV, you need to include the CSV plus any CRDs and a package.yaml file into a operator-registry pod. These steps are defined in the operator-registry repo of this org.
You can also find working examples of community submitted operators in the repo here: https://github.com/operator-framework/community-operators
We should update this repo with more up to date documentation and examples.

**Comment by hasbro17** [comment]
We've updated the instructions in #36 to include the step for creating the OperatorGroup.
But as @SamiSousa mentioned we're going make extensive updates to the OLM section to reflect the current workflow of installing an operator with OLM.

Closing this in favor of #37
