### ISSUE TITLE
Update the OLM section to use CatalogSource and Operator Registry

### ISSUE THREAD

**Issue by hasbro17** [operator-framework/getting-started#37]
The getting-started guide currently has instructions for applying a CSV directly to a namespace. This isn't the expected user experience for installing an operator with OLM today.

As a follow up to #36 the instructions should be updated to:
- Use the SDK generated CSV manifests instead of using the existing [outdated manifest](https://github.com/operator-framework/getting-started/blob/c85fc82fd3e3f2bcf23fa236c12096dc01df384f/memcachedoperator.0.0.1.csv.yaml#L36).
  - For the image field users will need to update the image to a more recent memcached-operator example. Either to one that they build and push, or one that is hosted at `quay.io/operator-framework/memcached-operator` based on the [samples memcached-operator](https://github.com/operator-framework/operator-sdk-samples/tree/master/memcached-operator).
- Have users build the operator registry image with their generated CSV
- Walkthrough creating a CatalogSource and Subscription to install the memcached-operator

/cc @SamiSousa

**Comment by hasbro17** [comment]
@SamiSousa I've pushed the latest image for the samples memcached-operator at [quay.io/operator-framework/sample-memcached-operator](https://quay.io/repository/operator-framework/sample-memcached-operator?tab=tags) so we can use that if needed.

**Comment by dmesser** [comment]
Agree, the docs are mixing concepts of deploying the Operator using its manifests manually as well as using OLM to give it as CSV. While we plan to re-introduce CSV handling outside of a catalog the getting started guide should **also** show how to build a catalog.

**Comment by camilamacedo86** [comment]
Hi folks IMHO: The image `quay.io/jzelinskie/memcached-operator:v0.0.1` should be in the operator-framework org instead of. 

Also, the steps to do it show be doc here; https://github.com/operator-framework/community-operators/blob/master/docs/testing-operators.md

**Comment by camilamacedo86** [comment]
Hi @hasbro17, 

The OLM steps as its example are updated now. In this way, I think that we can close safely this one. However, please feel free to re-open and add here what we should be done to close it if you believe that any further action related to this issue still required. 

Also, I really think that would be a great idea we provide the docker images for the samples. So, I tracked this idea here https://github.com/operator-framework/operator-sdk-samples/issues/88. Please, feel free to contribute with too.
