### ISSUE TITLE
Generated CSV manifests are missing required description and displayName fields 

### ISSUE THREAD

**Issue by hasbro17** [operator-framework/getting-started#39]
In the section [Generate an Operator Manifest](https://github.com/operator-framework/getting-started#generate-an-operator-manifest) users are told to generate their CSV manifests via the SDK's `operator-sdk olm-catalog gen-csv` command.

As of `v0.8.0` the CSV will not generate the `spec.customresourcedefinitions.owned.displayName` and `spec.customresourcedefinitions.owned.description` which are required by OLM:
```console
$ oc apply -f deploy/olm-catalog/memcached-operator/0.0.1/memcached-operator.v0.0.1.clusterserviceversion.yaml
spec.customresourcedefinitions.owned.displayName in body is required
spec.customresourcedefinitions.owned.description in body is required
``` 

Until this can be fixed upstream in the SDK the docs should point out this required change in the generated manifests.

**Comment by hasbro17** [comment]
@estroz Can you reference the related issue/PR in the SDK if we have one for this already.

**Comment by estroz** [comment]
https://github.com/operator-framework/operator-sdk/issues/1259 discusses this issue.

**Comment by camilamacedo86** [comment]
Hi @hasbro17, 

Note that we update the OLM steps as it example which make it more clear. Also, the need to populated dynamic the fields `spec.customresourcedefinitions` are tracked in  https://github.com/operator-framework/operator-sdk/issues/1132 already and as we described in https://github.com/operator-framework/operator-sdk/issues/2071  the project has other plans in place to try to improve the user experience and make this process easier, for example, by implementing a new API lib to validate it. See https://github.com/operator-framework/api.

So, it shows to me that we could address the points raised here and is quite safe to close this one. In this way, I am closing it. However, please feel free to re-open if you see that something else need to get done with.
