### ISSUE TITLE
CSV keeps pending due to "CSV missing minimum kube version specification"

### ISSUE THREAD

**Issue by gyliu513** [operator-framework/getting-started#43]
I followed the document at https://github.com/operator-framework/getting-started/blob/master/README.md#deploy-the-operator to deploy the CSV, but the CSV keeps pending due to following errors of `CSV missing minimum kube version specification`.

```json
root@gyliu-dev1:~/test# kubectl get ClusterServiceVersion memcachedoperator.v0.0.1 -o json | jq '.status'
{
  "certsLastUpdated": null,
  "certsRotateAt": null,
  "conditions": [
    {
      "lastTransitionTime": "2019-08-19T06:57:16Z",
      "lastUpdateTime": "2019-08-19T06:57:16Z",
      "message": "requirements not yet checked",
      "phase": "Pending",
      "reason": "RequirementsUnknown"
    },
    {
      "lastTransitionTime": "2019-08-19T06:57:16Z",
      "lastUpdateTime": "2019-08-19T06:57:16Z",
      "message": "one or more requirements couldn't be found",
      "phase": "Pending",
      "reason": "RequirementsNotMet"
    }
  ],
  "lastTransitionTime": "2019-08-19T06:57:16Z",
  "lastUpdateTime": "2019-08-19T06:57:16Z",
  "message": "one or more requirements couldn't be found",
  "phase": "Pending",
  "reason": "RequirementsNotMet",
  "requirementStatus": [
    {
      "group": "operators.coreos.com",
      "kind": "ClusterServiceVersion",
      "message": "CSV missing minimum kube version specification",
      "name": "memcachedoperator.v0.0.1",
      "status": "NotPresent",
      "version": "v1alpha1"
    },
    {
      "group": "apiextensions.k8s.io",
      "kind": "CustomResourceDefinition",
      "message": "CRD is present and Established condition is true",
      "name": "memcacheds.cache.example.com",
      "status": "Present",
      "uuid": "51b571c2-c24e-11e9-be38-0242d843cc68",
      "version": "v1beta1"
    },
    {
      "dependents": [
        {
          "group": "rbac.authorization.k8s.io",
          "kind": "PolicyRule",
          "message": "namespaced rule:{\"verbs\":[\"*\"],\"apiGroups\":[\"\"],\"resources\":[\"pods\",\"services\",\"endpoints\",\"persistentvolumeclaims\",\"events\",\"configmaps\",\"secrets\"]}",
          "status": "Satisfied",
          "version": "v1beta1"
        },
        {
          "group": "rbac.authorization.k8s.io",
          "kind": "PolicyRule",
          "message": "namespaced rule:{\"verbs\":[\"get\"],\"apiGroups\":[\"\"],\"resources\":[\"namespaces\"]}",
          "status": "NotSatisfied",
          "version": "v1beta1"
        },
        {
          "group": "rbac.authorization.k8s.io",
          "kind": "PolicyRule",
          "message": "namespaced rule:{\"verbs\":[\"*\"],\"apiGroups\":[\"apps\"],\"resources\":[\"deployments\",\"daemonsets\",\"replicasets\",\"statefulsets\"]}",
          "status": "Satisfied",
          "version": "v1beta1"
        },
        {
          "group": "rbac.authorization.k8s.io",
          "kind": "PolicyRule",
          "message": "namespaced rule:{\"verbs\":[\"get\",\"create\"],\"apiGroups\":[\"monitoring.coreos.com\"],\"resources\":[\"servicemonitors\"]}",
          "status": "Satisfied",
          "version": "v1beta1"
        },
        {
          "group": "rbac.authorization.k8s.io",
          "kind": "PolicyRule",
          "message": "namespaced rule:{\"verbs\":[\"update\"],\"apiGroups\":[\"apps\"],\"resources\":[\"deployments/finalizers\"],\"resourceNames\":[\"memcached-operator\"]}",
          "status": "Satisfied",
          "version": "v1beta1"
        },
        {
          "group": "rbac.authorization.k8s.io",
          "kind": "PolicyRule",
          "message": "namespaced rule:{\"verbs\":[\"*\"],\"apiGroups\":[\"cache.example.com\"],\"resources\":[\"*\"]}",
          "status": "Satisfied",
          "version": "v1beta1"
        }
      ],
      "group": "",
      "kind": "ServiceAccount",
      "message": "Policy rule not satisfied for service account",
      "name": "memcached-operator",
      "status": "PresentNotSatisfied",
      "version": "v1"
    }
  ]
}
```

**Comment by gyliu513** [comment]
```
root@gyliu-dev1:~/test# kubectl version
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.0", GitCommit:"641856db18352033a0d96dbc99153fa3b27298e5", GitTreeState:"clean", BuildDate:"2019-03-25T15:53:57Z", GoVersion:"go1.12.1", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.4", GitCommit:"c27b913fddd1a6c480c229191a087698aa92f0b1", GitTreeState:"clean", BuildDate:"2019-03-20T16:54:39Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}
```
```
root@gyliu-dev1:~/test# operator-sdk version
operator-sdk version: v0.10.0-3-g9d6ffdd, commit: 9d6ffddcd86fba2bf56191b55f61215675aee3f1
```

**Comment by camilamacedo86** [comment]
Hi @gyliu513,

I just would like to share with you that I am waiting for we are able to merge the PR operator-framework/operator-sdk#1162 because then we can update the CSV example easily. This file shows outdated.

If you wish to check some examples to see how it works, I'd recommend giving a look in the files used by the opers which are published in the https://operatorhub.io/ https://github.com/operator-framework/community-operators/tree/master/upstream-community-operators.

**Comment by camilamacedo86** [comment]
Hi @gyliu513, 

The PR https://github.com/operator-framework/operator-sdk/pull/2095 will add in the CSV file he spec with a place holder in order to remember that it is required and avoid this scenario.

**Comment by gyliu513** [comment]
Thanks @camilamacedo86 , got it. Any latest example that I can try?

**Comment by camilamacedo86** [comment]
HI @gyliu513, 

My proposal to this doc to try to make what/how it is required to do more understandable and easier is in the PR https://github.com/operator-framework/getting-started/pull/57. You can check the changes [here](https://github.com/operator-framework/getting-started/blob/422e105ebc5a94e91b085140d47305a08c859c64/README.md). It is essential to highlight that it is just an idea/suggestion and needs the consent of the others too, however, you are free to check. 

So, please let me know if this PR help you have a better understanding and get it done. See that new links/examples are associated with it as well. Note that to check it I'd suggested to you follow up all using the SDK version v0.11.0.

Currently, the SDK can help you integrate your project with OLM by generating the CSV file, but it needs to be updated as described there. Then, it is required to create the OLM bundle and follow its steps to test the project locally. 

The project has some PRs and proposals for improvements in these areas well. See, for example, https://github.com/operator-framework/operator-sdk/pull/1162(it may can help you to generate the file) and https://github.com/operator-framework/operator-sdk/pull/1913.

I hope that it helps you with.

**Comment by camilamacedo86** [comment]
HI @gyliu513,

In order to help you with. See a [PR](https://github.com/operator-framework/operator-sdk-samples/pull/82) to upgrade the Memcached sample to use SDK 0.11. 

Also, if you wish to try to use operator-framework/operator-sdk#1162 this PR to help you generate the CSV file in your projects, the see [here](https://github.com/dev4devs-com/postgresql-operator) my personal project which I used this PR to do the file. May it helps you check how to use the [metadata](https://github.com/dev4devs-com/postgresql-operator/blob/master/pkg/apis/postgresql/v1alpha1/database_types.go#L22) in the type to do that.  This project is available in the operatorHub and you can check/test/use it as well if you wish. 

I hope that it helps you with.

**Comment by gyliu513** [comment]
@camilamacedo86 I will do some test for this. Thanks!

**Comment by camilamacedo86** [comment]
Hi @gyliu513,

The OLM steps in the Getting Started as its example was updated in the #57 in order to address this issue as well. Then, I am closing this task. However, please, feel free to re-open if you see that still required.
