### ISSUE TITLE
Running sample memcached operator fails with build errors

### ISSUE THREAD

**Issue by draghuram** [operator-framework/getting-started#53]
After following all the steps listed in the README, I tried to run the operator on local cluster but it failed with some build errors. Here is the command and the output:

```
$ operator-sdk up local --namespace=default
INFO[0000] Running the operator locally.                
INFO[0000] Using namespace default.                     
build github.com/example-inc/memcached-operator/cmd/manager: cannot load sigs.k8s.io/controller-runtime/pkg/log: module sigs.k8s.io/controller-runtime@latest (v0.2.2) found, but does not contain package sigs.k8s.io/controller-runtime/pkg/log
Error: failed to build operator to run locally: (failed to exec []string{"go", "build", "-o", "build/_output/bin/memcached-operator-local", "github.com/example-inc/memcached-operator/cmd/manager"}: exit status 1)
Usage:
  operator-sdk up local [flags]
...
...
```

Go version:
```
$ go version
go version go1.13 linux/amd64
```

Is there some issue with the versioning of dependencies?

**Comment by camilamacedo86** [comment]
Hi @draghuram,

The go 1.13 is not supported yet. Could you please check it with the version 1.12?

**Comment by draghuram** [comment]
Thanks for quick response. Let me try with 1.12.

**Comment by draghuram** [comment]
Hi, the command now fails with a slightly different error:
```
$ operator-sdk up local --namespace=default
INFO[0000] Running the operator locally.                
INFO[0000] Using namespace default.                     
go: finding sigs.k8s.io/controller-runtime/pkg/log latest
go: finding sigs.k8s.io/controller-runtime/pkg latest
build github.com/example-inc/memcached-operator/cmd/manager: cannot load sigs.k8s.io/controller-runtime/pkg/log: cannot find module providing package sigs.k8s.io/controller-runtime/pkg/log
Error: failed to build operator to run locally: (failed to exec []string{"go", "build", "-o", "build/_output/bin/memcached-operator-local", "github.com/example-inc/memcached-operator/cmd/manager"}: exit status 1)
```
Go version:
```
$ go version
go version go1.12.9 linux/amd64
```

**Comment by draghuram** [comment]
[go.mod.txt](https://github.com/operator-framework/getting-started/files/3658747/go.mod.txt)

**Comment by draghuram** [comment]
@estroz, I attached go.mod file as requested in the discussion forum.

**Comment by estroz** [comment]
Do you have the import path `sigs.k8s.io/controller-runtime/pkg/log` anywhere in  your project?

```
$ grep -R "sigs.k8s.io/controller-runtime/pkg/log" . /dev/null
```

**Comment by draghuram** [comment]
Here is the output:
```
$ grep -R "sigs.k8s.io/controller-runtime/pkg/log" . /dev/null
./pkg/controller/memcached/memcached_controller.go:     logf "sigs.k8s.io/controller-runtime/pkg/log"
```
Note that I haven't made any changes in the generated project other than copying over the controller file as mentioned in the README.

**Comment by estroz** [comment]
Ah you copied over the `master` branch version, which uses controller-runtime v0.2.0 (different package structure). Please copy over [this version](https://github.com/operator-framework/operator-sdk/blob/v0.10.0/example/memcached-operator/memcached_controller.go.tmpl) instead.

I'll make a note about branch versioning in this repo, thanks.

**Comment by draghuram** [comment]
Thanks @estroz. Using the right controller file helped. The build errors are resolved.
