### ISSUE TITLE
unsupported type invalid type for invalid type

### ISSUE THREAD

**Issue by degenaro** [operator-framework/getting-started#65]
Likely noob user error.  Please advise.

```
[kube@abbey-road memcached-operator]$ pwd
/home/kube/go/src/memcached-operator
[kube@abbey-road memcached-operator]$ operator-sdk add api --api-version=cache.example.com/v1alpha1 --kind=Memcached
INFO[0000] Generating api version cache.example.com/v1alpha1 for kind Memcached. 
INFO[0000] Created pkg/apis/cache/group.go              
INFO[0000] Created pkg/apis/cache/v1alpha1/memcached_types.go 
INFO[0000] Created pkg/apis/addtoscheme_cache_v1alpha1.go 
INFO[0000] Created pkg/apis/cache/v1alpha1/register.go  
INFO[0000] Created pkg/apis/cache/v1alpha1/doc.go       
INFO[0000] Created deploy/crds/cache.example.com_v1alpha1_memcached_cr.yaml 
INFO[0000] Running deepcopy code-generation for Custom Resource group versions: [cache:[v1alpha1], ] 
F0117 12:41:16.750338   29464 deepcopy.go:885] Hit an unsupported type invalid type for invalid type, from memcached-operator/pkg/apis/cache/v1alpha1.Memcached
```

**Comment by estroz** [comment]
Probably something to do with your project path. See https://github.com/kubernetes/kubernetes/issues/79149#issuecomment-504128650. Try moving your project to `$GOPATH/src/github.com/<some user>/memcached-operator` or out of `$GOPATH` completely.

**Comment by camilamacedo86** [comment]
It shows to be the same scenario of  https://github.com/operator-framework/operator-sdk/issues/2302

Please, @degenaro ensure that you are using go version 1.13+ as well. 

In this way, I am closing this one as a duplicate. However, If you still needing help please could you raise a new issue in https://github.com/operator-framework/operator-sdk? Also, please do not forget to fill the template with all info over your environment and add your go envs too.
