### ISSUE TITLE
no kind is registered for the type v1alpha1.Memcached in scheme

### ISSUE THREAD

**Issue by riponbanik** [operator-framework/getting-started#66]
While running locally, operator-sdk up local --namespace=default

getting the following error

INFO[0000] Running the operator locally.
INFO[0000] Using namespace default.
{"level":"info","ts":1579734188.498171,"logger":"cmd","msg":"Operator Version: 0.0.1"}
{"level":"info","ts":1579734188.4988022,"logger":"cmd","msg":"Go Version: go1.13.5"}
{"level":"info","ts":1579734188.4997938,"logger":"cmd","msg":"Go OS/Arch: linux/amd64"}
{"level":"info","ts":1579734188.5006425,"logger":"cmd","msg":"Version of operator-sdk: v0.12.0"}
{"level":"info","ts":1579734188.5113451,"logger":"leader","msg":"Trying to become the leader."}
{"level":"info","ts":1579734188.5177064,"logger":"leader","msg":"Skipping leader election; not running in a cluster."}
{"level":"info","ts":1579734189.072683,"logger":"controller-runtime.metrics","msg":"metrics server is starting to listen","addr":"0.0.0.0:8383"}
{"level":"info","ts":1579734189.0745957,"logger":"cmd","msg":"Registering Components."}
{"level":"info","ts":1579734189.0768316,"logger":"controller-runtime.controller","msg":"Starting EventSource","controller":"memcached-controller","source":"kind source: /, Kind="}
{"level":"error","ts":1579734189.0776124,"logger":"cmd","msg":"","error":"no kind is registered for the type v1alpha1.Memcached in scheme \"pkg/runtime/scheme.go:101\"","stacktrace":"github.com/go-logr/zapr.(*zapLogger).Error\n\t/home/riponb/ws/golang/pkg/mod/github.com/go-logr/zapr@v0.1.1/zapr.go:128\nmain.main\n\t/.../operators/example-inc/memcached-operator/cmd/manager/main.go:114\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:203"}
Error: failed to run operator locally: (failed to exec []string{"build/_output/bin/memcached-operator-local"}: exit status 1)

**Comment by riponbanik** [comment]
@camilamacedo86 need your help

**Comment by estroz** [comment]
@riponbanik I cannot reproduce your issue. You may have missed a step in the guide. I recommend going through it thoroughly again. If the problem persists, feel free to reopen this issue for triage.

**Comment by camilamacedo86** [comment]
Hi @riponbanik, 

The error is "no kind is registered for the type v1alpha1.Memcached in scheme" which means that the CRD was not applied. As @estroz said you missed a step in the getting started which is : 

`$ kubectl create -f deploy/crds/cache.example.com_memcacheds_crd.yaml`
