### ISSUE TITLE
Inconsistency between the “getting-started” doc and the sample repo

### ISSUE THREAD

**Issue by liurui-1** [operator-framework/getting-started#72]
In the “getting-started” doc user will create code in “github.com/example-inc/memcached-operator/”. While the controller code in the sample repo is using another package path. For example in “https://github.com/operator-framework/operator-sdk-samples/blob/master/go/memcached-operator/pkg/controller/memcached/memcached_controller.go”, it is using “cachev1alpha1 "github.com/operator-framework/operator-sdk-samples/go/memcached-operator/pkg/apis/cache/v1alpha1"”.
The build is OK if user simply copies the sample code of “memcached_controller.go”. But it will report error message such as "Could not get ObjectKinds for OwnerType" and "no kind is registered for the type v1alpha1.Memcached…” at runtime.

Or at least the doc should mention this issue to avoid this unexpected failure.

**Comment by camilamacedo86** [comment]
HI @liurui-1, 

The Getting Started is a tutorial and the Sample is an example quite similar. However, they are not identical. The sample is good for users are able to check a quite similar project and figure out how things work.

**Comment by camilamacedo86** [comment]
I am closing it as sorted out. However, please feel free to ping us if you think that it should be re-opened.
