### ISSUE TITLE
Link on the doc go to 404 

### ISSUE THREAD

**Issue by michaelcourcy** [operator-framework/getting-started#73]
Hi 

the links for installing the operator sdk and olm on the readme go to a 404 page : 

```
**Requirements**: Please make sure that the Operator SDK is [installed][doc_sdk_install_instr] on the development machine. 

Additionally, the Operator Lifecycle Manager must be [installed][doc_olm_install_instr] in the cluster (1.8 or above to support the apps/v1beta2 API group) before running this guide.
```

Both link lead to a 404 page. That was not the case one week ago. 

```
doc_sdk_install_instr -> https://github.com/operator-framework/operator-sdk/blob/master/doc/user-guide.md#install-the-operator-sdk-cli
doc_olm_install_instr -> https://github.com/operator-framework/operator-lifecycle-manager/blob/master/doc/install/install.md
```

Thanks

**Comment by estroz** [comment]
@michaelcourcy thanks for bringing this to our attention. We're in the process of migrating docs, will update these links ASAP.

**Comment by q42jaap** [comment]
@estroz Any news on what the links will be?

**Comment by camilamacedo86** [comment]
Hi @q42jaap, 

The idea is we have in the future a Getting Started in https://sdk.operatorframework.io/.
Regards the break links raised: 

- doc_sdk_install_instr -> https://github.com/operator-framework/operator-sdk/blob/master/doc/user-guide.md#install-the-operator-sdk-cli

It is in now in: https://sdk.operatorframework.io/docs/install-operator-sdk/

 - doc_olm_install_instr -> https://github.com/operator-framework/operator-lifecycle-manager/blob/master/doc/install/install.md

It is now in: https://github.com/operator-framework/operator-lifecycle-manager/blob/master/doc/install/install.md

If you wish help with and update this doc so far, please feel free to do a PR against the master ok with the changes.

**Comment by camilamacedo86** [comment]
I am closing this one since all here shows sorted out. Feel free to ping us to re-open it if you wish and to ping me in your pr against its master with the fix in the links if you would like to collab to fix that anyway.

**Comment by estroz** [comment]
We need to fix these links since this repo still exists.
