### ISSUE TITLE
Link on the readme go to 404

### ISSUE THREAD

**Issue by shrinaththube** [operator-framework/getting-started#74]
Hello 

The link for `required fields` under [generate-an-operator-manifest](https://github.com/operator-framework/getting-started#generate-an-operator-manifest) section on the readme go to a 404 page. Same for [testing-locally](https://github.com/operator-framework/getting-started#testing-locally) section

The current link for`required fields`: https://github.com/operator-framework/operator-sdk/blob/master/doc/user/olm-catalog/generating-a-csv.md#csv-fields

Correction to the  link could be: https://github.com/operator-framework/operator-sdk/blob/docs-website/doc/user/olm-catalog/generating-a-csv.md#csv-fields

Thank you!!

**Comment by demonCoder95** [comment]
I've fixed this in my PR #76 . This along with all the broken links in the README doc.
