### ISSUE TITLE
Latest getting started instructions fail (missing repo type - only helm/ansible available)

### ISSUE THREAD

**Issue by a-roberts** [operator-framework/getting-started#79]
Hi, I'm using Docker Desktop, follow the main readme, so specifically:

```
brew install operator-sdk (wait around 15 min)

curl -L https://github.com/operator-framework/operator-lifecycle-manager/releases/download/0.15.1/install.sh -o install.sh
chmod +x install.sh
./install.sh 0.15.1 

mkdir -p $GOPATH/src/github.com/example-inc/
cd $GOPATH/src/github.com/example-inc/
export GO111MODULE=on
operator-sdk new memcached-operator <-- this wants a type - I'd actually like to use go and not Ansible or Helm
cd memcached-operator

...

      --type string                 Type of operator to initialize (choices: "ansible" or "helm")

Global Flags:
      --verbose   Enable verbose logging

FATA[0000] required flag(s) "type" not set  
...

```

also the comment about matching versions is misleading as there's only up to a 0.15.x release for operator-sdk, but operator-sdk version gives 0.19.0.

If I'm supposed to use the same versions for them both, how? Are they now out of sync (what's available for brew and GitHub)?

FWIW my Go version is 1.14.5 and I'm running on a Mac, thanks

**Comment by a-roberts** [comment]
Update: found https://sdk.operatorframework.io/docs/golang/quickstart/, I'll be using this instead - looks like the instructions/commands have changed dramatically since there's operator-sdk on brew of version 0.19 (suggesting either this repo requires an update or is no longer the main source of ref?)

**Comment by camilamacedo86** [comment]
Hi @a-roberts, 

Yes, we are working on the changes planned for 1.0.0 which will change the layout of the projects in order to aligned and integrate it with kubebuilder. These instructions are outdated and the idea is to update them add it to the website as soon as possible.
