### ISSUE TITLE
Broken Link: Operator SDK installation link

### ISSUE THREAD

**Issue by tanalam2411** [operator-framework/getting-started#80]
Under section: [Build an operator using the Operator SDK](https://github.com/operator-framework/getting-started#build-an-operator-using-the-operator-sdk) , the link is broken at line `Requirements: Please make sure that the Operator SDK is installed` .

Link `installed` is pointing to - https://sdk.operatorframework.io/docs/install-operator-sdk/, should be pointing - https://sdk.operatorframework.io/docs/installation/install-operator-sdk/

**Comment by jmccormick2001** [comment]
the getting-started repo is out of date, soon to be archived,  and replaced with the following documentation:
https://sdk.operatorframework.io/

that site's documentation source is found in the following repo:
https://github.com/operator-framework/operator-sdk

**Comment by tanalam2411** [comment]
Thank You
