### ISSUE TITLE
Getting Started outdated for Operator SDK v1.x

### ISSUE THREAD

**Issue by msatyan** [operator-framework/getting-started#81]
Since the Operator SDK v1.x has released, it will be great help if you could update the [Getting Started](https://github.com/operator-framework/getting-started) page (on the master) based on this version. The information in the page is mostly outdated, the project creation itself will fail.

```
operator-sdk new memcached-operator
```
There is no `new` command with this version, for example this is what a user gets.

```
operator-sdk new memcached-operator
Error: unknown command "new" for "operator-sdk"
Run 'operator-sdk --help' for usage.
FATA[0000] unknown command "new" for "operator-sdk"
```
- [operator-sdk v1.x CLI](https://sdk.operatorframework.io/docs/cli/)
- [Quickstart guid v1.x](https://sdk.operatorframework.io/docs/building-operators/golang/quickstart/)
There is a Quick start guide for the release version, look like it also has incomplete instruction, it give me error during `make install` phase. Operator SDK is a grate tool, without right set of information it will be difficult for fairly new users like me to make use of it. Thanks a lot for the grate work.

```
make install
-- -- -- -- --
-- -- -- -- --
/work/dev/go/proj1/bin/kustomize build config/crd | kubectl apply -f -
Warning: kubectl apply should be used on resource created by either kubectl create --save-config or kubectl apply
The CustomResourceDefinition "memcacheds.cache.example.com" is invalid: status.storedVersions[0]: Invalid value: "v1alpha1": must appear in spec.versions
make: *** [install] Error 1
```

I am plan to use the release version (well, plan to study the concept by using this released version)
```
operator-sdk  version
operator-sdk version: "v1.0.0", commit: "d7d5e0cd6cf5468bb66e0849f08fda5bf557f4fa", kubernetes version: "v1.18.2", go version: "go1.13.11 linux/amd64", GOOS: "linux", GOARCH: "amd64"
```

**Comment by camilamacedo86** [comment]
hI @msatyan, 

Thank you for your input, however, the plan is deprecated and archive this repo. 
A lot of improvements as been planned as part of the milestone  [Post 1.0 docs](https://github.com/operator-framework/operator-sdk/milestone/12).

Duplicated of https://github.com/operator-framework/operator-sdk/issues/3741

c/c @joelanford @asmacdo @jmrodri
